name: ni+di+ti
epsilon: 0.01568627450980392
step_size: 0.00392156862745098
steps: 10
clamp_min: 0.0
clamp_max: 1.0
random_start: false
targeted: false
loss_name: cross_entropy
ignore_index: 255
extra:
  momentum_decay: 1.0
  resize_rate: 0.9
  diversity_prob: 0.7
  ti_kernel_size: 5
  ti_sigma: 3.0
