name: ni-fgsm
epsilon: 0.01568627450980392
step_size: 0.00392156862745098
steps: 10
clamp_min: 0.0
clamp_max: 1.0
random_start: false
targeted: false
loss_name: cross_entropy
ignore_index: 255
extra:
  momentum_decay: 1.0
